### ISSUE TITLE
Issue with higher modes in ENIGMAIMR 

### ISSUE THREAD

**Issue by sum33it** [gwnrtools/gwnrtools#16]
Hi! I am trying to choose the modes with the option `modes_to_use` but it seems that the this is not working. When I try to plot waveforms with dominant mode `'modes_to_use':[(2,2)]` and without this option, there seems to be no difference in the output.

**Comment by prayush** [comment]
![image](https://github.com/gwnrtools/gwnrtools/assets/7142969/5e43a669-4ee3-451a-8699-49d3aa07f415)

**Comment by Akash-Maurya-0899** [comment]
Hi @sum33it! May I know the value of the inclination ($\iota$) you are generating the waveform at? If you are generating the waveform at $\iota=0$ (which is the default function value), then since $\prescript{}{-2}Y_{\ell m}(\iota=0, \phi) = 0$, for $(\ell, m)=(3, \pm3), (4, \pm 4)$, the above result is expected (although the output will become messy, but you can set `verbose=2` in the function to see this yourself).

When I'm generating the waveform at, say, $\iota=\pi/3$, I'm indeed getting different results for `modes_to_use=[(2,2)]` and the default `modes_to_use=[(2,2), (3,3), (4,4)]`.

**Comment by sum33it** [comment]
Hi @Akash-Maurya-0899 Thanks for your message. You are right. I was using $i=\pi$. It gives me different results for $i \neq 0, \pi $.
